#include "xparameters.h"
#include "xuartlite.h"
#include "xtmrctr.h"
#include "xstatus.h"
#include <string.h>
#include <stdint.h>

// Taken from the xparameters.h generated by Vitis for the UART Lite IP core
#define UART_DEVICE_ID XPAR_AXI_UARTLITE_0_BASEADDR
#define TIMER_DEVICE_ID XPAR_AXI_TIMER_0_BASEADDR
#define TIMER_NUM 0

#define MAX_LENGTH 2048
#define KERNEL_SIZE 64

XUartLite UartLite;
XTmrCtr Timer;

float signal[MAX_LENGTH] = {
    #include "signal_data.inc"
};

float kernel[KERNEL_SIZE] = {
    #include "kernel_data.inc"
};

float result[MAX_LENGTH - KERNEL_SIZE + 1];

volatile int data_length = 1024;
volatile int kernel_length = 3;
volatile int output_length = 1022;

static int init_uart(void) {
    int status = XUartLite_Initialize(&UartLite, UART_DEVICE_ID);
    if (status != XST_SUCCESS) {
        return status;
    }

    XUartLite_ResetFifos(&UartLite);
    return XST_SUCCESS;
}

static int init_timer(void) {
    int status = XTmrCtr_Initialize(&Timer, TIMER_DEVICE_ID);
    if (status != XST_SUCCESS) {
        return status;
    }

    // Configure timer 0 as a down counter
    XTmrCtr_SetOptions(&Timer, TIMER_NUM, XTC_AUTO_RELOAD_OPTION);

    // Count Up
    XTmrCtr_SetResetValue(&Timer, TIMER_NUM, 0);

    return XST_SUCCESS;
}

static void send_u32(uint32_t value) {
    u8 data_buffer[4];
    memcpy(data_buffer, &value, sizeof(uint32_t));

    XUartLite_Send(&UartLite, data_buffer, 4);
    while (XUartLite_IsSending(&UartLite)) {
    }
}

static void send_float(float value) {
    u8 data_buffer[4];
    memcpy(data_buffer, &value, sizeof(float));

    XUartLite_Send(&UartLite, data_buffer, 4);
    while (XUartLite_IsSending(&UartLite)) {
    }
}

static uint32_t recv_u32_blocking(void) {
    u8 buffer[4];
    int bytes = 0;

    while (bytes < 4) {
        int count = XUartLite_Recv(&UartLite, &buffer[bytes], 4 - bytes);
        bytes += count;
    }

    uint32_t value;
    memcpy(&value, buffer, sizeof(uint32_t));
    return value;
}

int main() {
    int status;

    status = init_uart();
    if (status != XST_SUCCESS) {
        return -1;
    }

    status = init_timer();
    if (status != XST_SUCCESS) {
        return -1;
    }

    while (1) {

        uint32_t data = recv_u32_blocking();

        if (data != 0xFFFFFFFFu) {
            continue;
        }

        // Reset and start timer
        XTmrCtr_Reset(&Timer, TIMER_NUM);
        XTmrCtr_Start(&Timer, TIMER_NUM);

        // Perform convolution
        for (int i = 0; i < output_length; i++) {
            float sum = 0.0f;
            for (int j = 0; j < kernel_length; j++) {
                sum += signal[i + j] * kernel[j];
            }
            result[i] = sum;
        }

        // Read elapsed cycles
        uint32_t elapsed = XTmrCtr_GetValue(&Timer, TIMER_NUM);
        XTmrCtr_Stop(&Timer, TIMER_NUM);

        send_u32(elapsed);

        // Send results
        for (int i = 0; i < output_length; i++) {
            send_float(result[i]);
        }
    }
    return 0;
}