#include "xparameters.h"
#include "xuartlite.h"
#include <string.h>

// Taken from the xparameters.h generated by Vitis for the UART Lite IP core
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define MAX_LENGTH 2048
#define KERNEL_SIZE 64

// Hex representation of ascii characters for UART
#define SIGN 0x5349474E
#define KERN 0x4B45524E
#define DATAERROR 0x44455252
#define WEIGHTSERROR 0x57455252
#define START 0x53545254
#define DONE 0x444F4E45

XUartLite UartLite;
float signal[MAX_LENGTH];
float kernel[KERNEL_SIZE];
float result[MAX_LENGTH - KERNEL_SIZE + 1];
volatile int data_length = 1;
volatile int kernel_length = 1;
volatile int output_length = 1;

int main() {
    XUartLite_Initialize(&UartLite, XPAR_XUARTLITE_0_BASEADDR);
    u8 buffer[4];
    int bytes = 0;

    while (1) {
        int err = 0;
        float data = 0;
        data_length = 0;
        kernel_length = 0;
        output_length = 0;
        bytes = 0;

        while (1) {
            while (bytes < 4) {
                int count = XUartLite_Recv(&UartLite, &buffer[bytes], 4 - bytes);
                bytes += count;
            }

            bytes = 0;
            memcpy(&data, buffer, sizeof(float));

            if (data == -1.0f){
                break;
            } else if (data_length >= MAX_LENGTH) {
                err = 1;
                break;
            }
                
            signal[data_length] = data;
            data_length += 1;
        }

        if (err) {
            u8 error[4] = {0x44, 0x45, 0x52, 0x52}; // "DATAERROR"
            XUartLite_Send(&UartLite, error, 4);
            while (XUartLite_IsSending(&UartLite));
            continue; // restart loop
        }

        // Send "SIGN"
        u8 sign[4] = {0x53, 0x49, 0x47, 0x4E};
        XUartLite_Send(&UartLite, sign, 4);
        while (XUartLite_IsSending(&UartLite));

        bytes = 0;

        while (1) {
            while (bytes < 4){
                int count = XUartLite_Recv(&UartLite, &buffer[bytes], 4 - bytes);
                bytes += count;
            }

            bytes = 0;
            memcpy(&data, buffer, sizeof(float));

            if (data == -1.0f){
                break;
            } else if (kernel_length >= KERNEL_SIZE) {
                err = 1;
                break;
            }

            kernel[kernel_length] = data;
            kernel_length += 1;
        }

        if (err) {
            u8 error[4] = {0x57, 0x45, 0x52, 0x52}; // "WEIGHTSERROR"
            XUartLite_Send(&UartLite, error, 4);
            while (XUartLite_IsSending(&UartLite));
            continue; // restart loop
        }

        // Send "KERN"
        u8 kern[4] = {0x4B, 0x45, 0x52, 0x4E};
        XUartLite_Send(&UartLite, kern, 4);
        while (XUartLite_IsSending(&UartLite));

        output_length = data_length - kernel_length + 1;

        u8 start[4] = {0x53, 0x54, 0x52, 0x54}; // "START"
        XUartLite_Send(&UartLite, start, 4);
        while (XUartLite_IsSending(&UartLite));

        // Perform convolution
        for (int i = 0; i < output_length; i++) {
            float sum = 0.0f;
            for (int j = 0; j < kernel_length; j++) {
                sum += signal[i + j] * kernel[j];
            }
            result[i] = sum;
        }

        u8 done[4] = {0x44, 0x4F, 0x4E, 0x45}; // "DONE"
        XUartLite_Send(&UartLite, done, 4);
        while (XUartLite_IsSending(&UartLite));

        // Send results
        for (int i = 0; i < output_length; i++) {
            u8 data_buffer[4];
            memcpy(data_buffer, &result[i], sizeof(float));
            XUartLite_Send(&UartLite, data_buffer, 4);
            while (XUartLite_IsSending(&UartLite));
        }

    }
    return 0;
}
